version: '3'
services:
  zk:
    image: "confluentinc/cp-zookeeper:latest"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    expose:
      - 2181
    ports:
      - 2181:2181
    network_mode: host
  kafka:
    image: "confluentinc/cp-kafka:latest"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: 127.0.0.1:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_BROKER_ID: 1
      JMX_PORT: 5600
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - 9092:9092
      - 5600:5600
    depends_on:
      - zk
    network_mode: host
  schema:
    image: "confluentinc/cp-schema-registry:latest"
    depends_on:
      - kafka
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 127.0.0.1:2181
      SCHEMA_REGISTRY_HOST_NAME: 127.0.0.1
      SCHEMA_REGISTRY_LISTENERS: http://127.0.0.1:8081
    network_mode: host
    ports:
      - 8081:8081